# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Replace <track> with the track name
# Replace <image-name> with an image to run the jobs on
# Replace <action to setup tooling> with a github action to setup tooling on the image
# Replace <install dependencies> with a cli command to install the dependencies
#
# Find Github Actions to setup tooling here:
# - https://github.com/actions/?q=setup&type=&language=
# - https://github.com/actions/starter-workflows/tree/main/ci
# - https://github.com/marketplace?type=actions&query=setup
#
# Requires scripts:
# - bin/test

name: harbour / Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Install Harbour
        run: |
            sudo apt update
            sudo apt -y install libc6-dev
            sudo apt -y install curl libpcre3-dev libpcre3 libssl-dev
            sudo apt -y install libslang2-dev libgpm-dev libncurses5-dev libncursesw5-dev
            curl -LJO https://raw.githubusercontent.com/ajborla/download-harbour-deb/main/harbour_3.2.0-1_amd64.deb
            sudo apt -y install ./harbour_3.2.0-1_amd64.deb

      - name: Verify all exercises
        run: bin/verify-exercises
